@startuml
hide footbox

participant "Patient Demographics\nConsumer" as Client
participant "Patient Demographics\nSupplier" as Server

== Query ==
activate Client
activate Server
Client -> Server : Query Patient Resource
Server -> Client : Query Patient Resource Response

== Retrieve ==
Client -> Server : Retrieve Patient Resource
Server -> Client : Retrieve Patient Resource Response
deactivate Server
deactivate Client

@enduml
