@startuml MPI-Based-Process-Flow-in-PDQm-Profile
hide footbox
skinparam ParticipantPadding 50
participant "Patient Demographics\nConsumer" as Client
participant "Patient Demographics\nSupplier" as Server

Client -> Server : Patient Demographics\nMatch [ITI-119]
activate Server
activate Client
Server -> Client : Patient Demographics\nMatch Response
deactivate Client
deactivate Server
@enduml
