@startuml
hide footbox

Participant "Patient\nDemographics\nConsumer" as Client1
Participant "Patient\nDemographics\nSupplier/Consumer" as Server1
Participant "Patient\nDemographics\nSupplier" as Server2

Activate Server1
Activate Client1
Activate Server2

Client1 -> Server1 : Mobile Patient Demographics\nQuery [ITI-78]
Server1 -> Server2 : Patient Demographics\nQuery [ITI-21]\nor Patient Demographics\nQuery for HL7v3 [ITI-47]

Server2 -> Server1 : Patient Demographics\nQuery [ITI-21]\nor Patient Demographics\nQuery for HL7v3 [ITI-47] Response
Server1 -> Client1 : Mobile Patient Demographics\nQuery [ITI-78] Response

@enduml
