id: IHE.ITI.PDQm
canonical: https://profiles.ihe.net/ITI/PDQm
version: 0.1.0
name: IHE_PDQm
title: "Patient Demographics Query for mobile (PDQm)"
status: draft
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: url
        value: https://www.ihe.net/ihe_domains/it_infrastructure/
  - name: David Pyke
    telecom:
      - system: email
        value: dpyke@ainq.com
description: The Patient Demographics Query for Mobile (PDQm) Profile defines a lightweight RESTful interface to a patient demographics supplier leveraging technologies readily available to mobile applications and lightweight browser based applications.
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2020+
releaseLabel: ci-build


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  special-url: 
    - urn:ihe:event-type-code


resources:
  Patient/Patient-MohrAlissa-Red:
    name: Patient Alissa Mohr (Red)
    description: Patient Mohr Alisa in IHE Red Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice:
    name: Patient Alice Mohr
    description: 'Patient Mohr Alice with all IHE Domain identifiers, note: this is just a consolidated identifier example will all identifiers from all the IHE domains equivalent to a golden patient, however a golden patient is not the scope of PIXm, see the IHE PMIR profile' 
    exampleBoolean: true
  Patient/Patient-MohrAlice-Red:
    name: Patient Alice Mohr (Red)
    description: Patient Mohr Alice in IHE Red Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice-Green:
    name: Patient Alice Mohr (Green)
    description: Patient Mohr Alice in IHE Green Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice-Blue:
    name: Patient Alice Mohr (Blue)
    description: Patient Mohr Alice in IHE Blue Domain
    exampleBoolean: true
  Patient/Patient-MaidenAlice-Red:
    name: Patient Maiden Alice (Red)
    description: Patient Maiden Alice in IHE Red Domain
    exampleBoolean: true


pages:
  index.md:
    title: 1:38. Patient Demographics Query for Mobile
    generation: markdown
  actors_and_transactions.md:
    title: 1:38.1 Actors and Transactions
    generation: markdown
  actor_options.md: 
    title: 1:38.2 Actor Options
    generation: markdown
  required_groupings.md:
    title: 1:38.3 Required Groupings
    generation: markdown
  overview.md:
    title: 1:38.4 Overview
    generation: markdown
  security_considerations.md:
    title: 1:38.5 Security Considerations
    generation: markdown
  grouping.md:
    title: 1:38.6 Cross-Profile Considerations
    generation: markdown
  ITI-78.md:
    title: 2:3.78 Mobile Patient Demographics Query [ITI-78]
    generation: markdown
  appendixm.md:
    title: Appendix M Patient Demographics Query Implementation Guidance
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown

menu:
  PDQm Home: index.html
  Volume 1:
    Actors and Transactions: actors_and_transactions.html
    Actor Options: actor_options.html
    Required Groupings: required_groupings.html
    Overview: overview.html
    Security Considerations: security_considerations.html
    Cross-Profile Considerations: grouping.html
  Volume 2:
    "Mobile Patient Demographics Query [ITI-78]": ITI-78.html
  Appendix:
    "M:Patient Demographics Query Implementation Guidance": appendixm.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
