id: IHE.ITI.PDQm
canonical: http://profiles.ihe.net/ITI/PDQm
version: 2.2.2
name: IHE_PDQm
title: "Patient Demographics Query for mobile (PDQm)"
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
description: The Patient Demographics Query for Mobile (PDQm) Profile defines a lightweight RESTful interface to a patient demographics supplier leveraging technologies readily available to mobile applications and lightweight browser based applications.
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2020+
releaseLabel: ci-build


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  special-url: 
    - urn:ihe:event-type-code


resources:
  Patient/Patient-MohrAlissa-Red:
    name: Patient Alissa Mohr (Red)
    description: Patient Mohr Alisa in IHE Red Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice:
    name: Patient Alice Mohr
    description: 'Patient Mohr Alice with all IHE Domain identifiers, note: this is just a consolidated identifier example will all identifiers from all the IHE domains equivalent to a golden patient, however a golden patient is not the scope of PIXm, see the IHE PMIR profile' 
    exampleBoolean: true
  Patient/Patient-MohrAlice-Red:
    name: Patient Alice Mohr (Red)
    description: Patient Mohr Alice in IHE Red Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice-Green:
    name: Patient Alice Mohr (Green)
    description: Patient Mohr Alice in IHE Green Domain
    exampleBoolean: true
  Patient/Patient-MohrAlice-Blue:
    name: Patient Alice Mohr (Blue)
    description: Patient Mohr Alice in IHE Blue Domain
    exampleBoolean: true
  Patient/Patient-MaidenAlice-Red:
    name: Patient Maiden Alice (Red)
    description: Patient Maiden Alice in IHE Red Domain
    exampleBoolean: true


pages:
  index.md:
    title: Patient Demographics Query for Mobile
    generation: markdown
  volume-1.md:
    title: 1:38 Patient Demographics Query for Mobile (PDQm)
    generation: markdown
  ITI-78.md:
    title: 2:3.78 Mobile Patient Demographics Query [ITI-78]
    generation: markdown
  testplan.md:
    title: PDQm Test Plan
    generation: markdown
  issues.md:
    title: PDQm Open and Closed issues
    generation: markdown

menu:
  PDQm Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1381-pdqm-actors-and-transactions
    Actor Options: volume-1.html#1382-pdqm-actor-options
    Required Groupings: volume-1.html#1383-pdqm-required-actor-grouping
    Overview: volume-1.html#1384-pdqm-overview
    Security Considerations: volume-1.html#1385-pdqm-security-considerations
    Cross-Profile Considerations: volume-1.html#1386-pdqm-cross-profile-considerations    
  Volume 2:
    "Mobile Patient Demographics Query [ITI-78]": ITI-78.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
