id: PDQm.ihe.net
canonical: https://profiles.ihe.net/PDQm
version: 0.1.0
name: Patient-Demographics-Query-for-Mobile
title: "Patient Demographics Query for Mobile"
status: draft
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: url
        value: https://www.ihe.net/ihe_domains/it_infrastructure/
  - name: David Pyke
    telecom:
      - system: email
        value: dpyke@ainq.com
description: The Patient Demographics Query for Mobile (PDQm) Profile defines a lightweight RESTful interface to a patient demographics supplier leveraging technologies readily available to mobile applications and lightweight browser based applications.
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

copyrightYear: 2020+
releaseLabel: Rev. 2.2 – Trial Implementation

pages:
  index.md:
    title: 38. Patient Demographics Query for Mobile
    generation: markdown
  actors_and_transactions.md:
    title: 38.1 Actors and Transactions
    generation: markdown
  actor_options.md: 
    title: 38.2 Actor Options
    generation: markdown
  required_groupings.md:
    title: 38.3 Required Groupings
    generation: markdown
  overview.md:
    title: 38.4 Overview
    generation: markdown
  usecases.md:
    title: 38.4.2 Use Cases
    generation: markdown
  security_considerations.md:
    title: 38.5 Security Considerations
    generation: markdown
  grouping.md:
    title: 38.6 Cross-Profile Considerations
    generation: markdown
  ITI-78.md:
    title: 3.78 Mobile Patient Demographics Query [ITI-78]
    generation: markdown
  appendixm.md:
    title: Appendix M Patient Demographics Query Implementation Guidance
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown

menu:
  IG Home: index.html
  Volume 1:
    Actors and Transactions: actors_and_transactions.html
    Actor Options: actor_options.html
    Required Groupings: required_groupings.html
    Overview: overview.html
    Use Cases: usecases.html
    Security Considerations: security_considerations.html
    Cross-Profile Considerations: grouping.html
  Volume 2:
    Mobile Patient Demographics Query: ITI-78.html
  Appendix:
    Patient Demographics Query Implementation Guidance: appendixm.html
  Artifacts: artifacts.html
